"""add menus table

Revision ID: b686b1a38ef2
Revises: 3eb81cd3f427
Create Date: 2026-08-01 19:52:20.491267

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b686b1a38ef2"
down_revision: str | Sequence[str] | None = "3eb81cd3f427"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menus",
        sa.Column("menu_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("menu_name", sa.String(length=50), nullable=False),
        sa.Column("menu_parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="생성 시각 (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="수정 시각 (UTC)",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(),
            nullable=True,
            comment="논리 삭제 시각 (UTC). NULL 이면 미삭제",
        ),
        sa.PrimaryKeyConstraint("menu_id", name=op.f("pk_menus")),
        sa.UniqueConstraint(
            "menu_parent_id", "menu_name", "deleted_at", name="uq_menus_parent_name"
        ),
    )
    op.create_index("ix_menus_deleted_at", "menus", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_menus_menu_parent_id"), "menus", ["menu_parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_menus_menu_parent_id"), table_name="menus")
    op.drop_index("ix_menus_deleted_at", table_name="menus")
    op.drop_table("menus")
    # ### end Alembic commands ###
