"""update post image model

Revision ID: 1829bc9d8c4a
Revises: 8c26dc833443
Create Date: 2026-09-03 19:29:30.031991

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1829bc9d8c4a"
down_revision: str | Sequence[str] | None = "8c26dc833443"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("parent_comment_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_comments_parent_comment_id"), "comments", ["parent_comment_id"], unique=False
    )
    op.drop_constraint(op.f("fk_comments_post_id_posts"), "comments", type_="foreignkey")
    op.drop_constraint(op.f("fk_comments_author_id_users"), "comments", type_="foreignkey")
    op.add_column(
        "posts_image", sa.Column("image_original_path", sa.String(length=500), nullable=False)
    )
    op.add_column(
        "posts_image", sa.Column("image_content_path", sa.String(length=500), nullable=False)
    )
    op.add_column(
        "posts_image", sa.Column("image_thumbnail_path", sa.String(length=500), nullable=False)
    )
    op.drop_column("posts_image", "image_path")
    op.alter_column(
        "users",
        "user_is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default="1",
        comment="False 면 로그인 및 인증이 거부된다",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        comment=None,
        existing_comment="False 면 로그인 및 인증이 거부된다",
        existing_nullable=False,
    )
    op.add_column("posts_image", sa.Column("image_path", mysql.VARCHAR(length=500), nullable=False))
    op.drop_column("posts_image", "image_thumbnail_path")
    op.drop_column("posts_image", "image_content_path")
    op.drop_column("posts_image", "image_original_path")
    op.create_foreign_key(
        op.f("fk_comments_author_id_users"), "comments", "users", ["author_id"], ["user_id"]
    )
    op.create_foreign_key(
        op.f("fk_comments_post_id_posts"),
        "comments",
        "posts",
        ["post_id"],
        ["post_id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_comments_parent_comment_id"), table_name="comments")
    op.drop_column("comments", "parent_comment_id")
    # ### end Alembic commands ###
