"""add posts image

Revision ID: d439f5babf47
Revises: d4394054ec4a
Create Date: 2026-08-12 17:50:47.720853

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d439f5babf47"
down_revision: str | Sequence[str] | None = "d4394054ec4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts_image",
        sa.Column("image_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="생성 시각 (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="수정 시각 (UTC)",
        ),
        sa.PrimaryKeyConstraint("image_id", name=op.f("pk_posts_image")),
    )
    op.create_index(op.f("ix_posts_image_post_id"), "posts_image", ["post_id"], unique=False)
    op.alter_column(
        "users",
        "user_email",
        existing_type=mysql.VARCHAR(length=255),
        comment="로그인 ID 로 사용하는 이메일",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "user_nickname",
        existing_type=mysql.VARCHAR(length=50),
        comment="표시 이름",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_nickname",
        existing_type=mysql.VARCHAR(length=50),
        comment=None,
        existing_comment="표시 이름",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "user_email",
        existing_type=mysql.VARCHAR(length=255),
        comment=None,
        existing_comment="로그인 ID 로 사용하는 이메일",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_posts_image_post_id"), table_name="posts_image")
    op.drop_table("posts_image")
    # ### end Alembic commands ###
